replicaCount: 1

image:
  repository: sharmila231/
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  environment: dev

resources: {}

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false